// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rcpp_locmax
LogicalVector rcpp_locmax(NumericVector x, int halfWindow);
RcppExport SEXP _MSExample_rcpp_locmax(SEXP xSEXP, SEXP halfWindowSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type halfWindow(halfWindowSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_locmax(x, halfWindow));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_MSExample_rcpp_locmax", (DL_FUNC) &_MSExample_rcpp_locmax, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_MSExample(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
